---
kind: Service
apiVersion: v1
metadata:
  name: chekkan-com
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "7dc1d3c00-ffc5-4758-a69f-bcb71b4a4fa9"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app: chekkan-ghost
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 2368
    - name: https
      protocol: TCP
      port: 443
      targetPort: 2368
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chekkan-deployment
spec:
  selector:
    matchLabels:
      app: chekkan-ghost
  replicas: 1
  template:
    metadata:
      labels:
        app: chekkan-ghost
    spec:
      containers:
        - name: ghost
          image: ghost:3.35.5-alpine
          ports:
            - containerPort: 2368
              protocol: TCP
          env:
            #   # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
            - name: url
              value: https://chekkan.editcafe.net
