---
kind: Service
apiVersion: v1
metadata:
  name: chekkan-com
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "7dc1d3c00-ffc5-4758-a69f-bcb71b4a4fa9"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app: chekkan-ghost
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 2368
    - name: https
      protocol: TCP
      port: 443
      targetPort: 2368
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chekkan-deployment
spec:
  selector:
    matchLabels:
      app: chekkan-ghost
  replicas: 1
  template:
    metadata:
      labels:
        app: chekkan-ghost
    spec:
      containers:
        - name: ghost
          image: chekkan/ghost-cloudinary@sha256:0b7116027cfc18cc865bce82703ea3ff67fcc81296a4fbe89eda246539311449
          ports:
            - containerPort: 2368
              protocol: TCP
          env:
            #   # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
            - name: url
              value: https://chekkan.editcafe.net
            - name: CLOUDINARY_URL
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: cloudinaryUrl
            - name: database__client
              value: mysql
            - name: database__connection__host
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: host
            - name: database__connection__port
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: port
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: username
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: password
            - name: database__connection__database
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: database
            - name: database__connection__ssl
              value: "true"
