---
kind: Service
apiVersion: v1
metadata:
  name: chekkan-com
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "fdc9946f-f874-4d14-9dc6-4945a95338d9"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app: chekkan-ghost
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 2368
    - name: https
      protocol: TCP
      port: 443
      targetPort: 2368
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chekkan-deployment
spec:
  selector:
    matchLabels:
      app: chekkan-ghost
  replicas: 1
  template:
    metadata:
      labels:
        app: chekkan-ghost
    spec:
      containers:
        - name: ghost
          image: chekkan/ghost-cloudinary@sha256:69bb70a66bf3f1398ddd57479e03b0850e15a46b99d42f233ab1b93f66caaf04
          ports:
            - containerPort: 2368
              protocol: TCP
          env:
            #   # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
            - name: url
              value: https://chekkan.com
            - name: CLOUDINARY_URL
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: cloudinaryUrl
            - name: database__client
              value: mysql
            - name: database__connection__host
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: host
            - name: database__connection__port
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: port
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: username
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: password
            - name: database__connection__database
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: database
            - name: database__connection__ssl
              value: "true"
            - name: mail__transport
              value: SMTP
            - name: mail__options__service
              value: Mailgun
            - name: mail__options__host
              value: smtp.mailgun.org
            - name: mail__options__port
              value: "587"
            - name: mail__options__auth__user
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: smtpUser
            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  name: chekkan-db-secret
                  key: smtpPassword
